### ISSUE TITLE
New release to support GHC 9.6.1

### ISSUE THREAD

**Issue by jonathanknowles** [obsidiansystems/commutative-semigroups#11]
Hi there

I'm wondering whether it's possible to make a new release to Hackage? (After https://github.com/obsidiansystems/commutative-semigroups/pull/10, I'm guessing everything should just work?)

I have a few packages that depend (transitively) on `commutative-semigroups`: I'd love to be able to provide support for GHC 9.6.1 and `base` version `4.18`. (Obviously, I can tell people to write `--allow-newer` as a workaround, so this is not urgent!)

Best wishes!

Jonathan

**Comment by jonathanknowles** [comment]
Hi @Taneb

Just wondering if you're able to upload a new version of `commutative-semigroups` to hackage to support GHC 9.6.1?

Would be happy to help in any way if I can.
 
Many thanks!
 
Jonathan

**Comment by ali-abrar** [comment]
@jonathanknowles all set. https://hackage.haskell.org/package/commutative-semigroups-0.1.0.1

**Comment by jonathanknowles** [comment]
> @jonathanknowles all set. https://hackage.haskell.org/package/commutative-semigroups-0.1.0.1

@ali-abrar that's great news. Many thanks!🙏
