### ISSUE TITLE
New release to support GHC 9.8?

### ISSUE THREAD

**Issue by jonathanknowles** [obsidiansystems/commutative-semigroups#13]
Hi there

Would it be possible to publish a new (or updated) version of `commutative-semigroups` on Hackage, to support the GHC `9.8` series (`base` major version `4.19`)?

Many thanks!

Jonathan

Context: the latest release of `commutative-semigroups` on Hackage ([0.1.0.1](https://hackage.haskell.org/package/commutative-semigroups-0.1.0.1)) has the constraint `base < 4.19`.

**Comment by jonathanknowles** [comment]
@Ericson2314 
@ali-abrar 

Sorry to ping you directly, but just wondering if it's possible to published a new (or updated) release on Hackage? 🙏🏻 

Many thanks!
Jonathan

**Comment by blamario** [comment]
Released as version 0.1.0.2
