### ISSUE TITLE
Make Hackage revision to support `base-4.20.0.0` and GHC `9.10`.

### ISSUE THREAD

**Issue by jonathanknowles** [obsidiansystems/commutative-semigroups#21]
Hi there!

Please would it be possible to make a revision on Hackage to support [`base-4.20.0.0`](https://hackage.haskell.org/package/base-4.20.0.0) and GHC `9.10`?

The latest Hackage version ([commutative-semigroups-2.0](https://hackage.haskell.org/package/commutative-semigroups-0.2)) currently has these bounds:
```cabal
  build-depends:       base >= 4.6 && < 4.20,
```

It seems like it should just be a matter of making Hackage reflect what's already in this repository:
https://github.com/obsidiansystems/commutative-semigroups/blob/48b3be3d9681dfa4a87fd4b12f50e68357553161/commutative-semigroups.cabal#L27

Many thanks!

**Comment by blamario** [comment]
Fixed by https://github.com/obsidiansystems/commutative-semigroups/pull/22 instead.

**Comment by jonathanknowles** [comment]
@blamario thanks!
