### ISSUE TITLE
Instances for GHC boot packages?

### ISSUE THREAD

**Issue by endgame** [obsidiansystems/commutative-semigroups#3]
https://github.com/blamario/monoid-subclasses/pull/35 proposes to add a couple of orphan instances:

* ` instance Ord a => Commutative (Set.Set a)`
* `instance Commutative IntSet.IntSet`

ISTM that `monoid-subclasses` is a bit of an odd place for them, and that we could depend on and provide instances for boot packages like `containers` without making this package feel too "heavy"

Ping @Taneb , as `groups` currently depends only on `base`, and he may have opinions.

**Comment by Ericson2314** [comment]
@Taneb, how do you feel about this? `monoid-subclasses` is fine doing the orphans, but if you don't mind the departure from minimality we could put them here too.

**Comment by Taneb** [comment]
My gut feeling is, roughly, "hnnnng", but I don't have any actual objection. It seems like a good idea, at least until there's a second widespread Haskell implementation

**Comment by Ericson2314** [comment]
OK sounds good.

https://gitlab.haskell.org/ghc/ghc/-/wikis/Rehabilitating-Orphans-with-Order-theory Rest assured, I do care a lot about the "putting instances in arbitrary places just so they aren't orphans doesn't scale" problem. :)

**Comment by Ericson2314** [comment]
@endgame if you don't mind, I assigned you this one.
